=== MikhedVeronika/Parser-XML-XSD-with-web/src/main/resources/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="flower" type="tns:Flower" abstract="true"/>
    <element name="one-year-flower" type="tns:OneYearFlower" substitutionGroup="tns:flower"/>
    <element name="multi-year-flower" type="tns:MultiYearFlower" substitutionGroup="tns:flower"/>

    <complexType name="Flower">
        <sequence>
            <element name="name" type="string" />
            <element name="soil">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="PODZOLIC" />
                        <enumeration value="UNPAVED" />
                        <enumeration value="SOD_PODZOLIC"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="origin" type="string" />
            <element name="visual-parameters" type="tns:VisualParameters" />
            <element name="growing-tips" type="tns:GrowingTips"/>
            <element name="multiplying">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="LEAF"/>
                        <enumeration value="STALK" />
                        <enumeration value="SEED" />
                        <enumeration value="BULB" />
                    </restriction>
                </simpleType>
            </element>

        </sequence>
        <attribute name="id" type="tns:IdFlower" use="required"/>
    </complexType>

    <complexType name="OneYearFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="flowering-days-count" type="positiveInteger" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="MultiYearFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="age-years" type="positiveInteger" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="leaf-color">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="LIGHT_GREEN" />
                        <enumeration value="GREEN" />
                        <enumeration value="YELLOW" />
                    </restriction>
                </simpleType>
            </element>
            <element name="flower-color">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="WHITE" />
                        <enumeration value="BLUE" />
                        <enumeration value="LIGHT_BLUE" />
                        <enumeration value="GREEN" />
                        <enumeration value="YELLOW" />
                        <enumeration value="RED" />
                        <enumeration value="ORANGE" />
                        <enumeration value="PINK" />
                        <enumeration value="VIOLET" />
                    </restriction>
                </simpleType>
            </element>
            <element name="average-size-cm" type="positiveInteger" />
        </sequence>
    </complexType>

    <complexType name="GrowingTips">
        <sequence>
            <element name="required-temperature" type="positiveInteger"/>
            <element name="lightening">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="HELIOPHILOUS" />
                        <enumeration value="NEUTRAL" />
                        <enumeration value="NOT_HELIOPHILOUS" />
                    </restriction>
                </simpleType>
            </element>
            <element name="week-watering-ml" type="positiveInteger" />
        </sequence>
    </complexType>

    <simpleType name="IdFlower">
        <restriction base="ID">
            <pattern value="F[1-9][0-9]*"/>
        </restriction>
    </simpleType>
</schema>

=== MikhedVeronika/Parser-XML-XSD-with-web/data/flowers.xml
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">
    <one-year-flower id="F1">
        <name>Tulip</name>
        <soil>UNPAVED</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <leaf-color>LIGHT_GREEN</leaf-color>
            <flower-color>RED</flower-color>
            <average-size-cm>40</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>26</required-temperature>
            <lightening>HELIOPHILOUS</lightening>
            <week-watering-ml>800</week-watering-ml>
        </growing-tips>
        <multiplying>BULB</multiplying>
        <flowering-days-count>30</flowering-days-count>
    </one-year-flower>

    <multi-year-flower id="F2">
        <name>Clover</name>
        <soil>SOD_PODZOLIC</soil>
        <origin>Russia</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>PINK</flower-color>
            <average-size-cm>25</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>20</required-temperature>
            <lightening>NEUTRAL</lightening>
            <week-watering-ml>1000</week-watering-ml>
        </growing-tips>
        <multiplying>SEED</multiplying>
        <age-years>2</age-years>
    </multi-year-flower>


    <one-year-flower id="F3">
        <name>Hyacinth</name>
        <soil>UNPAVED</soil>
        <origin>Greece</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>BLUE</flower-color>
            <average-size-cm>35</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>25</required-temperature>
            <lightening>HELIOPHILOUS</lightening>
            <week-watering-ml>900</week-watering-ml>
        </growing-tips>
        <multiplying>BULB</multiplying>
        <flowering-days-count>17</flowering-days-count>
    </one-year-flower>

    <multi-year-flower id="F4">
        <name>Lily of the Valley</name>
        <soil>PODZOLIC</soil>
        <origin>Belarus</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>WHITE</flower-color>
            <average-size-cm>22</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>20</required-temperature>
            <lightening>NEUTRAL</lightening>
            <week-watering-ml>700</week-watering-ml>
        </growing-tips>
        <multiplying>STALK</multiplying>
        <age-years>3</age-years>
    </multi-year-flower>

    <multi-year-flower id="F5">
        <name>Rose</name>
        <soil>UNPAVED</soil>
        <origin>Belarus</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>YELLOW</flower-color>
            <average-size-cm>55</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>25</required-temperature>
            <lightening>HELIOPHILOUS</lightening>
            <week-watering-ml>1500</week-watering-ml>
        </growing-tips>
        <multiplying>STALK</multiplying>
        <age-years>2</age-years>
    </multi-year-flower>
    
    <multi-year-flower id="F6">
        <name>Daisy</name>
        <soil>PODZOLIC</soil>
        <origin>Latvia</origin>
        <visual-parameters>
            <leaf-color>LIGHT_GREEN</leaf-color>
            <flower-color>WHITE</flower-color>
            <average-size-cm>15</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>23</required-temperature>
            <lightening>NOT_HELIOPHILOUS</lightening>
            <week-watering-ml>1000</week-watering-ml>
        </growing-tips>
        <multiplying>STALK</multiplying>
        <age-years>1</age-years>
    </multi-year-flower>
    
    <one-year-flower id="F7">
        <name>Carnation</name>
        <soil>SOD_PODZOLIC</soil>
        <origin>Russia</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>RED</flower-color>
            <average-size-cm>45</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>25</required-temperature>
            <lightening>NOT_HELIOPHILOUS</lightening>
            <week-watering-ml>1200</week-watering-ml>
        </growing-tips>
        <multiplying>SEED</multiplying>
        <flowering-days-count>55</flowering-days-count>
    </one-year-flower>

    <multi-year-flower id="F8">
        <name>Geranium</name>
        <soil>UNPAVED</soil>
        <origin>Poland</origin>
        <visual-parameters>
            <leaf-color>YELLOW</leaf-color>
            <flower-color>ORANGE</flower-color>
            <average-size-cm>27</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>25</required-temperature>
            <lightening>NEUTRAL</lightening>
            <week-watering-ml>1050</week-watering-ml>
        </growing-tips>
        <multiplying>SEED</multiplying>
        <age-years>4</age-years>
    </multi-year-flower>
    
    <multi-year-flower id="F9">
        <name>Cyclamen</name>
        <soil>SOD_PODZOLIC</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <leaf-color>GREEN</leaf-color>
            <flower-color>PINK</flower-color>
            <average-size-cm>20</average-size-cm>
        </visual-parameters>
        <growing-tips>
            <required-temperature>23</required-temperature>
            <lightening>NEUTRAL</lightening>
            <week-watering-ml>150</week-watering-ml>
        </growing-tips>
        <multiplying>STALK</multiplying>
        <age-years>1</age-years>
    </multi-year-flower>
</flowers>
